// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKgHCAlO2e2DVNmi_cGCkktrY-l12G6tc',
    appId: '1:856417063081:web:20c725e8d565b1b5bb19b8',
    messagingSenderId: '856417063081',
    projectId: 'ma-1101204298-b361b',
    authDomain: 'ma-1101204298-b361b.firebaseapp.com',
    storageBucket: 'ma-1101204298-b361b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3hkvprDjeKRCywNwKf7vWser2tXMfvSw',
    appId: '1:856417063081:android:b78afb0d5bd02f27bb19b8',
    messagingSenderId: '856417063081',
    projectId: 'ma-1101204298-b361b',
    storageBucket: 'ma-1101204298-b361b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpnCtxBu44o8g2doA0se61JMH7DNa2jEs',
    appId: '1:856417063081:ios:dc73112bf8f7d529bb19b8',
    messagingSenderId: '856417063081',
    projectId: 'ma-1101204298-b361b',
    storageBucket: 'ma-1101204298-b361b.appspot.com',
    iosClientId: '856417063081-bjhhe02qfjp3a42a3v9dts8lfhdqnuef.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpnCtxBu44o8g2doA0se61JMH7DNa2jEs',
    appId: '1:856417063081:ios:02061a4852705e10bb19b8',
    messagingSenderId: '856417063081',
    projectId: 'ma-1101204298-b361b',
    storageBucket: 'ma-1101204298-b361b.appspot.com',
    iosClientId: '856417063081-6copj7kc8pk8o9pegptivpcpfbsq3e40.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin.RunnerTests',
  );
}
